"""Core utilities for extracting 2D planes from CAESAR representations."""

from .caesar_adapter import (
    ArchiveMetadata,
    CaesarReference,
    LatentBlock,
    LatentVolume,
    extract_latent_blocks,
    inspect_npz,
    open_stored_npz_array,
    prepare_caesar_subset,
    run_caesar_reference,
    save_caesar_reference,
    stack_latent_depth,
)
from .geometry import (
    Plane,
    axis_aligned_plane,
    index_to_normalized,
    sample_plane,
    sample_volume,
)
from .datasets import (
    MultiBlockPlaneDataset,
    RandomPlaneDataset,
    ReferenceBlock,
    ReferenceSplit,
    discover_reference_artifacts,
    load_reference_blocks,
    load_reference_block,
    load_reference_collection,
    parse_index_specification,
    random_contained_plane,
    split_reference_blocks,
)
from .metrics import (
    error_decomposition,
    field_error_metrics,
    plane_decoder_error_decomposition,
    staged_error_decomposition,
)

__all__ = [
    "ArchiveMetadata",
    "CaesarReference",
    "LatentBlock",
    "LatentVolume",
    "MultiBlockPlaneDataset",
    "Plane",
    "RandomPlaneDataset",
    "ReferenceBlock",
    "ReferenceSplit",
    "axis_aligned_plane",
    "discover_reference_artifacts",
    "extract_latent_blocks",
    "error_decomposition",
    "field_error_metrics",
    "index_to_normalized",
    "inspect_npz",
    "load_reference_block",
    "load_reference_blocks",
    "load_reference_collection",
    "open_stored_npz_array",
    "prepare_caesar_subset",
    "plane_decoder_error_decomposition",
    "parse_index_specification",
    "random_contained_plane",
    "run_caesar_reference",
    "sample_plane",
    "sample_volume",
    "save_caesar_reference",
    "stack_latent_depth",
    "split_reference_blocks",
    "staged_error_decomposition",
]
